### ISSUE TITLE
Improve visibility of access rights section

### ISSUE THREAD

**Issue by ZenoLC** [tuwien-csd/damap-frontend#123]
**Changes**
The "set access rights" section in the storage step (currently 5), is very easy to overlook.
Improve visibility of this element such that the users will not be inclined to skip it.

**Assumptions**
The assumption here is that users have a hard time seeing this question and associating it to all datasets.

**Acceptance Criteria**
It is difficult to determine the acceptance criteria for such a visual/usability change. Ideally the tool should be tested with a new user, in order to check improvements.

**Comment by DerekMolnar** [comment]
![Image](https://github.com/tuwien-csd/damap-frontend/assets/150270835/181efd64-304c-47cf-b3b1-1c27b1a91596)

**Comment by DerekMolnar** [comment]
Let me connect with Christiane to get her feedback.  I don't think she has access to view your change.  @ZenoLC  could you give her access?

**Comment by ChristianeStork** [comment]
The problem is that it is not obvious to the user that we have two substeps: 1. select access rights, 2. choose storage. Working with headers may help, similar to step 3 and 6: 
5 Storage and backup... 
Text: This step helps you...
Header 1: Access rights
table access rights --> it would also help not to hyde the table: if it is visible right from the beginning, it can't be missed.
Header 2: Storage
... 
I would even rename the step to "Access, storage, and back-up during..." if that's possible. @TomMiksa: do you agree?
